version: "3.9"

services:
  runner:
    build: .
    image: sendpulse-whatsapp:latest
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      - SP_CLIENT_ID
      - SP_CLIENT_SECRET
      - SINCE
      - UNTIL
    volumes:
      - ./data:/app/out
    command: ["python", "app/sendpulse_whatsapp_pull.py"]

  # scheduler (futuro, desactivado)
  # scheduler:
  #   build: .
  #   image: sendpulse-whatsapp:latest
  #   user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
  #   env_file:
  #     - ${ENV_FILE:-.env}
  #   environment:
  #     - SP_CLIENT_ID=${SP_CLIENT_ID}
  #     - SP_CLIENT_SECRET=${SP_CLIENT_SECRET}
  #     - SINCE=${SINCE}
  #     - UNTIL=${UNTIL}
  #   volumes:
  #     - ./data:/app/out
  #     - ./app/crontab:/app/crontab:ro
  #   entrypoint: ["/bin/sh","-lc"]
  #   command: >
  #     "set -e;
  #      wget -qO /usr/local/bin/supercronic https://github.com/aptible/supercronic/releases/download/v0.2.29/supercronic-linux-amd64 &&
  #      chmod +x /usr/local/bin/supercronic &&
  #      supercronic /app/crontab"
